include:
  - project: 'shared/gitlab-ci-includes'
    ref: main
    file:
      - '/base.yml'
      - '/pypi-packages.yml'
      - '/debian-packages.yml'
      - '/python.yml'

variables:
  APTLY_BASE_REPOSITORY: common

stages:
  - test
  - build
  - publish

unit test and feature test:
  stage: test
  image: python:3.11
  script:
    - !reference [.add repositories, script]
    - apt-get -y install python3-psutil python3-requests python3-cached-property
    - pip install --no-cache-dir -r requirements/test.txt
    - PYTHONPATH=$CI_PROJECT_DIR/src:/usr/lib/python3/dist-packages pytest -n 10 -vvv --cov-branch --cov=cyberfusion.Common --cov-config=.coveragerc --cov-fail-under=100 --junitxml=report-pytest.xml
  artifacts:
    reports:
      junit: report-*.xml
